### ISSUE TITLE
missing dependencies: networkx, numpy, openpyxl

### ISSUE THREAD

**Issue by kurtdevos** [vallettea/koala#104]
Some packages are missing from the dependencies

```virtualenv koala-test
source koala-test/bin/activate
pip install koala2
python -c 'import koala2'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/experiments/koala/koala-venv/local/lib/python2.7/site-packages/koala/__init__.py", line 2, in <module>
    import ast
  File "/home/experiments/koala/koala-venv/local/lib/python2.7/site-packages/koala/ast/__init__.py", line 7, in <module>
    import networkx
ImportError: No module named networkx
```
running `pip install networkx numpy openpyxl` solves the issue.

**Comment by vallettea** [comment]
thanks for the contribution. We will add a `requirements.txt` very soon.
