### ISSUE TITLE
Multiline Formula fail to parse

### ISSUE THREAD

**Issue by musshorn** [vallettea/koala#139]
Attempt to parse the following code with

```
from koala.ExcelCompiler import ExcelCompiler

c = ExcelCompiler("bug.xlsx")
sp = c.gen_graph()
```

[bug.xlsx](https://github.com/anthill/koala/files/2355073/bug.xlsx)

Results in 
`SyntaxError: EOL while scanning string literal`

I think this can be fixed by updating [this line](https://github.com/anthill/koala/blob/master/koala/reader.py#L209) to also handle newline chars, or perhaps refactoring it into a general cleaning function in case other problematic characters emerge

**Comment by vallettea** [comment]
You have to save it as xls and try again

Envoyé de mon iPhone

**Comment by musshorn** [comment]
That seems to produce a different error?

```
___### Initializing Excel Compiler ###___
___### Reading Cells from XLSX ###___
Traceback (most recent call last):
  File "koala_test.py", line 9, in <module>
    c = ExcelCompiler(filename)
  File "C:\Python\Python36-32\lib\site-packages\koala\ExcelCompiler.py", line 28, in __init__
    self.cells = read_cells(archive, ignore_sheets, ignore_hidden)
  File "C:\Python\Python36-32\lib\site-packages\koala\reader.py", line 123, in read_cells
    for sheet in detect_worksheets(archive):
  File "C:\Python\Python36-32\lib\site-packages\koala\reader.py", line 272, in detect_worksheets
    rels = dict(read_rels(archive))
  File "C:\Python\Python36-32\lib\site-packages\koala\reader.py", line 230, in read_rels
    xml_source = archive.read(ARC_WORKBOOK_RELS)
  File "C:\Python\Python36-32\lib\zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "C:\Python\Python36-32\lib\zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "C:\Python\Python36-32\lib\zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'xl/_rels/workbook.xml.rels' in the archive"
```

**Comment by vallettea** [comment]
It's definitely a file format error. Ensure that your Excel file is recent and in standalone mode (open it with Excel and save, it should rewrite the file and the resulting file should be three of four times heavier).

**Comment by musshorn** [comment]
Reproduced it again on a different computer with a fresh install of Koala.
I made a new workbook and put the formula
```
=IF(TRUE,
FALSE,
TRUE)
```
in A1, saved it in Excel ( This was the resulting file [test.xlsx](https://github.com/anthill/koala/files/2356003/test.xlsx)) then ran the script. The file was saved with Excel 2016 version 1807 on Windows 10 x64.

Here's the full error

```
PS C:\dev> python .\koala_test.py
___### Initializing Excel Compiler ###___
___### Reading Cells from XLSX ###___
Nb of different functions 0
set()
___### Generating Graph ###___
Seeds 1 cells
Traceback (most recent call last):
  File "C:\Python\Python36-32\lib\site-packages\koala\Cell.py", line 179, in compile
    self.python_expression, '<string>', 'eval')
  File "<string>", line 1
    (self.eval_ref('Sheet1!
                          ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\koala_test.py", line 4, in <module>
    sp = c.gen_graph()
  File "C:\Python\Python36-32\lib\site-packages\koala\ExcelCompiler.py", line 92, in gen_graph
    cellmap, G = graph_from_seeds(seeds, self)
  File "C:\Python\Python36-32\lib\site-packages\koala\ast\__init__.py", line 616, in graph_from_seeds
    c1.compile() # cell compilation is done here because pointer ranges might update python_expressions
  File "C:\Python\Python36-32\lib\site-packages\koala\Cell.py", line 181, in compile
    raise Exception("Failed to compile cell %s with expression %s: %s\nFormula: %s" % (self.address(),self.python_expression,e, self.formula))
Exception: Failed to compile cell Sheet1!A1 with expression (self.eval_ref('Sheet1!
FALSE', ref = (1, 'A')) if True else self.eval_ref('Sheet1!
TRUE', ref = (1, 'A'))): EOL while scanning string literal (<string>, line 1)
Formula: IF(TRUE,
FALSE,
TRUE)
```

**Comment by vallettea** [comment]
Sorry, I really don't have time to check this at te moment.

**Comment by Brad-eki** [comment]
Can confirm @snipplets error message on his test.xlsx

I have saved his example file to be an Excel 97 - 2003 .xls and it does indeed grow in size, from 8KB to 25KB.

When I try again the following error is generated.
```
(koala) C:\Users\me\Documents\Python\koala_139>python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    c = ExcelCompiler("test.xls")
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\site-packages\koala2-0.0.29-py3.7.egg\koala\ExcelCompiler.py", line 28, in __init__
    self.cells = read_cells(archive, ignore_sheets, ignore_hidden)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\site-packages\koala2-0.0.29-py3.7.egg\koala\reader.py", line 123, in read_cells
    for sheet in detect_worksheets(archive):
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\site-packages\koala2-0.0.29-py3.7.egg\koala\reader.py", line 275, in detect_worksheets
    rels = dict(read_rels(archive))
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\site-packages\koala2-0.0.29-py3.7.egg\koala\reader.py", line 233, in read_rels
    xml_source = archive.read(ARC_WORKBOOK_RELS)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\zipfile.py", line 1428, in read
    with self.open(name, "r", pwd) as fp:
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\zipfile.py", line 1467, in open
    zinfo = self.getinfo(name)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\koala\lib\zipfile.py", line 1395, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'xl/_rels/workbook.xml.rels' in the archive"
```

I'm interested in learning how the cell parsing works so I'll use this to learn.

**Comment by Brad-eki** [comment]
So, in Koala/openpyxl/formula/tokenizer.py there is a function parse_whitespace(). It only addresses space characters.
```python
    def parse_whitespace(self):
        """
        Consume a string of consecutive spaces.

        Returns the number of spaces found. (Does not update self.offset).

        """
        assert self.formula[self.offset] == ' '
        self.items.append(Token(' ', Token.WSPACE))
        return self.WSPACE_RE.match(self.formula[self.offset:]).end()
```
In the current repo for the official project openpyxl/formula/tokenizer._parse_whitespace() we can see it manages newlines.

```python
    def _parse_whitespace(self):
        """
        Consume a string of consecutive spaces.

        Returns the number of spaces found. (Does not update self.offset).

        """
        assert self.formula[self.offset] in (' ', '\n')
        self.items.append(Token(self.formula[self.offset], Token.WSPACE))
        return self.WSPACE_RE.match(self.formula[self.offset:]).end()
```
There are  a bunch more changes as the official openpyxl has changed the paradigm for tokenizing and have comprehensively supported newlines in formulae.

Is there a reason we are relying on a copy of pyopenxl rather than having it as a dependency?

**Comment by Brad-eki** [comment]
Having a broader look at things, we don't seem to use the openpyxl tokenizer in Koala. It's there because we use openpyxl.formula.translate.Translator()

**Comment by Brad-eki** [comment]
I have modified the Koala tokenizer.py to be tolerant of "\n". Will put for ward a PR shortly.

**Comment by Brad-eki** [comment]
first attempt: commit e9961de

**Comment by Brad-eki** [comment]
I got too excited with cleaning up... this commit has passed the automated testing: fc1a5c8

**Comment by Brad-eki** [comment]
Hi @snipplets, This should be supported now. If this is still important to you, it would be great to hear how it is fixed, or how it need more work.

Cheers
