### ISSUE TITLE
math functions (sinus/radians etc.)

### ISSUE THREAD

**Issue by stefanslangen** [vallettea/koala#224]
Is it correct that some math functions are not supported yet if they occur in the Excel sheet (for example sinus, cosinus, radians etc.)? 

I am getting the following error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\koala\Spreadsheet.py", line 982, in cell_evaluate
    vv = eval(cell.compiled_expression)
  File "<string>", line 1, in <module>
NameError: name 'radians' is not defined

**Comment by Brad-eki** [comment]
@stefanslangen, the functions supported are largely listed here;
https://github.com/vallettea/koala/blob/master/koala/functions.json

In case that list hasn't been updated I have done a search through the code to see if they have been implemented. I have found those functions are not yet implemented.

You are welcome to implement them if you like. There is code in this commit which might inspire you as to how;
https://github.com/vallettea/koala/commit/3de965cb49733d34aca3873d4a7c553fa94fec9d

**Comment by danielsjf** [comment]
Listing the functions for future reference:
* COS
* COSH
* ACOS
* ACOSH
* IMCOS
* IMCOSH
* SIN
* SINH
* ASIN
* ASINH
* IMSIN
* IMSINH
* RADIANS

According to [this](https://support.office.com/en-us/article/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188) list, there are 476 known and documented excel [functions](https://github.com/vallettea/koala/files/3524707/functions.xlsx) (extracted in that file). Maybe we could write a small code to check how many of those functions we have implemented already.
